{
 "title": "auth-service - Metrics & Logs",
 "tags": [
  "microservices",
  "authentication-service",
  "devsecops"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "auth-service — CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"microservices\", pod=~\"authentication-service.*\", cpu=\"total\"}[5m])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "auth-service — RAM (MB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megabytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"microservices\", pod=~\"authentication-service.*\"}) by (pod) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "auth-service — Erreurs 5xx par route (/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"authentication-service\", status_code=~\"5..\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "auth-service — Logs erreurs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"microservices\", pod=~\"authentication-service.*\"} |~ \"(?i)login failed|register failed|change password failed\" [5m])"
    }
   ]
  },
  {
   "title": "auth-service — Latence p95 par route",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app=\"authentication-service\"}[5m])) by (le, route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "auth-service — Alerte: taux erreur 5xx (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_request_duration_seconds_count{app=\"authentication-service\", status_code=~\"5..\"}[5m])) / sum(rate(http_request_duration_seconds_count{app=\"authentication-service\"}[5m]))",
     "legendFormat": "taux erreur %"
    }
   ]
  }
 ]
}